# Generated by Django 4.0.7 on 2023-02-20 23:28

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name_app", models.CharField(blank=True, default="", max_length=255)),
                (
                    "logo_app",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.global_settings_logo_directory_path,
                    ),
                ),
                ("session_expire_time", models.IntegerField(default=60)),
                ("active_registration", models.BooleanField(default=True)),
                ("header_scripts", models.TextField(blank=True, null=True)),
                ("footer_scripts", models.TextField(blank=True, null=True)),
                ("body_scripts", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.user_profile_directory_path,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.CharField(default="en-us", max_length=5)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "date_format",
                    models.CharField(blank=True, default="dd-mm-yyyy", max_length=15),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
